name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java environment
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn package

    - name: Dockerize application
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: markhan01/spring-boot-ecommerce:${{ github.sha }}

    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v18.2
      with:
        aws-region: ${{ env.AWS_REGION }}
        application-name: Angular-Spring-Ecommerce
        environment-name: Angularspringecommerce-env
        version-label: ${{ github.sha }}
        image: markhan01/spring-boot-ecommerce:${{ github.sha }}
        access-key: ${{ env.AWS_ACCESS_KEY_ID }}
        secret-key: ${{ env.AWS_SECRET_ACCESS_KEY }}