name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java environment
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'

    - name: Build with Maven
      working-directory: ./backend/spring-boot-ecommerce
      run: mvn package

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Dockerize application
      uses: docker/build-push-action@v4
      with:
        context: ./backend/spring-boot-ecommerce
        push: false
        tags: spring-boot-ecommerce:${{ github.sha }}

    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        region: ${{ env.AWS_REGION }}
        application_name: Angular-Spring-Ecommerce
        environment_name: Angularspringecommerce-env
        version_label: ${{ github.sha }}
        aws_access_key: ${{ env.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        deployment_package: ./backend/spring-boot-ecommerce/target/spring-boot-ecommerce-0.0.1-SNAPSHOT.jar
